test: &default

  # Credentials for REST APIs
  client_id: AeceUxA79VTjDJ6AzNPsL6ufhDmPpbYyHYr1SUP-vw9Gkwvgu88mvHrIzO7z
  client_secret: EAqYuRBSkw1At84_DrIMJddvl3OMqallA0UxZR1toc1nnrqKEfe5SBXPe3Uy

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-48740994H8080701U
  username: payments_api1.zalpe.com
  password: S5RJKQ9RLTPADADE
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31Aii9lcKtUZeqZqK--YilDkC9pBw.
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  
 
    